version: 0.2

phases:
  install:
    commands:
      - cd vue-frontend
      - npm install
  build:
    commands:
      - npm run make

artifacts:
  files:
    - 'vue-frontend/dist/**/*'
    - 'text_processing_python/**/*'
    - 'build-scripts/*'
    - 'appspec.yml'
